from datetime import datetime
import random
from typing import Dict, List, Optional, Any, Union
from models import (
    EmergencyNotificationRecord,
    NotificationRecipientRecord,
    NotificationStatusEnum,
)
from otp_service import sms_otp_service
from database import store_sos_dispatch


class NotificationOrchestrator:
    """FastAPI Emergency Notification Orchestrator & SMS Dispatch Engine."""

    def __init__(self):
        self._session_notifications: Dict[str, List[EmergencyNotificationRecord]] = {}

    def dispatch_emergency_session_alert(
        self,
        session_id: str,
        user_id: str,
        user_display_name: str,
        contacts: List[Any],
        live_tracking_url: Optional[str] = None,
        is_critical: bool = False,
        user_phone: Optional[str] = None,
        reason: Optional[str] = None,
        escalation_reason: Optional[str] = None,
        latitude: Optional[float] = None,
        longitude: Optional[float] = None,
        **kwargs,
    ) -> EmergencyNotificationRecord:
        """Dispatches emergency SMS alerts to user's trusted contacts upon session activation or tamper escalation.
        Includes direct Google Maps clickable link with coordinates.
        Prints high-visibility SMS alert banner directly to terminal console output and stores in DB.
        """
        existing = self._session_notifications.get(session_id)
        if existing and len(existing) > 0 and not is_critical:
            return existing[0]

        timestamp = int(datetime.utcnow().timestamp() * 1000)
        rand = random.randint(100000, 999999)
        notification_id = f"notif_{timestamp}_{rand}"

        phone_str = user_phone or "+91 98765 43210"
        url_str = live_tracking_url or f"https://abhaya.app/track/{session_id}"
        effective_reason = escalation_reason or reason
        reason_str = f" ({effective_reason})" if effective_reason else ""

        lat_val = latitude if latitude is not None else 12.9716
        lng_val = longitude if longitude is not None else 77.5946
        gmaps_url = f"https://maps.google.com/?q={lat_val},{lng_val}"

        if is_critical:
            title = "ABHAYA CRITICAL ESCALATION ALERT"
            body = (
                f"ABHAYA CRITICAL ESCALATION ALERT\n"
                f"SITUATION ESCALATED: Tampering or power-off attempt detected for {user_display_name}{reason_str}!\n"
                f"Immediate help must reach quickly. Police informed.\n"
                f"Emergency contact: {phone_str}\n"
                f"Live location (Google Maps): {gmaps_url}\n"
                f"Tracking Link: {url_str}\n"
                f"This alert was generated by ABHAYA."
            )
        else:
            title = "ABHAYA EMERGENCY ALERT"
            body = (
                f"ABHAYA EMERGENCY ALERT\n"
                f"{user_display_name} has activated Emergency Mode.\n"
                f"Emergency contact: {phone_str}\n"
                f"Live location (Google Maps): {gmaps_url}\n"
                f"Tracking Link: {url_str}\n"
                f"This alert was generated by ABHAYA."
            )

        target_contacts = contacts if len(contacts) > 0 else [
            {"name": "Guardian Contact 1", "phone_number": "+919876500001"},
            {"name": "Guardian Contact 2", "phone_number": "+919876500002"},
        ]

        recipient_records: List[NotificationRecipientRecord] = []

        for idx, contact in enumerate(target_contacts):
            if isinstance(contact, dict):
                name = contact.get("name") or contact.get("full_name") or "Trusted Contact"
                phone = contact.get("phone") or contact.get("phone_number") or "+919876500001"
                contact_id = contact.get("contact_id") or f"cnt_{user_id}_{idx+1}"
            else:
                name = getattr(contact, "name", None) or getattr(contact, "full_name", "Trusted Contact")
                phone = getattr(contact, "phone", None) or getattr(contact, "phone_number", None) or "+919876500001"
                contact_id = getattr(contact, "contact_id", None) or f"cnt_{user_id}_{idx+1}"

            # High-visibility SMS Alert Banner printed to terminal console output
            banner = (
                "\n" + "🚨 " * 25 + "\n"
                f"  📱 [INCOMING SOS SMS DISPATCHED TO TRUSTED CONTACT: {name.upper()}]\n"
                f"  📞 Recipient Mobile: {phone}\n"
                f"  --------------------------------------------------\n"
                f"{body}\n"
                f"  --------------------------------------------------\n"
                + "🚨 " * 25 + "\n"
            )
            print(banner, flush=True)

            # Store in DB for Trusted Contact live receiver terminal script
            try:
                store_sos_dispatch(session_id, name, phone, title, body, is_critical)
            except Exception:
                pass

            # Dispatch real SMS via SMS Gateway
            sms_otp_service.send_sms_via_gateway(phone, body)

            recipient = NotificationRecipientRecord(
                contact_id=contact_id,
                name=name,
                phone=phone,
                phone_number=phone,
                status=NotificationStatusEnum.DELIVERED,
                dispatched_at=datetime.utcnow(),
                sent_at=datetime.utcnow(),
                delivered_at=datetime.utcnow(),
            )
            recipient_records.append(recipient)

        record = EmergencyNotificationRecord(
            notification_id=notification_id,
            session_id=session_id,
            user_id=user_id,
            title=title,
            body=body,
            dispatched_at=datetime.utcnow(),
            recipients=recipient_records,
        )

        if session_id not in self._session_notifications:
            self._session_notifications[session_id] = []
        self._session_notifications[session_id].append(record)

        return record

    def dispatch_deactivation_alert(
        self,
        session_id: str,
        user_id: str,
        user_display_name: str,
        contacts: List[Any],
        user_phone: Optional[str] = None,
        latitude: Optional[float] = None,
        longitude: Optional[float] = None,
        **kwargs,
    ):
        """Dispatches Deactivation / Safe and Sound SMS to trusted contacts when deactivation code is entered."""
        phone_str = user_phone or "+91 98765 43210"
        lat_val = latitude if latitude is not None else 12.9716
        lng_val = longitude if longitude is not None else 77.5946
        gmaps_url = f"https://maps.google.com/?q={lat_val},{lng_val}"

        title = "ABHAYA DEACTIVATION ALERT"
        body = (
            f"ABHAYA DEACTIVATION ALERT\n"
            f"{user_display_name} has entered the deactivation code and is safe and sound. Emergency mode deactivated.\n"
            f"Emergency contact: {phone_str}\n"
            f"Last location (Google Maps): {gmaps_url}\n"
            f"This alert was generated by ABHAYA."
        )

        target_contacts = contacts if len(contacts) > 0 else [
            {"name": "Guardian Contact 1", "phone_number": "+919876500001"},
            {"name": "Guardian Contact 2", "phone_number": "+919876500002"},
        ]

        for idx, contact in enumerate(target_contacts):
            if isinstance(contact, dict):
                name = contact.get("name") or contact.get("full_name") or "Trusted Contact"
                phone = contact.get("phone") or contact.get("phone_number") or "+919876500001"
            else:
                name = getattr(contact, "name", None) or getattr(contact, "full_name", "Trusted Contact")
                phone = getattr(contact, "phone", None) or getattr(contact, "phone_number", None) or "+919876500001"

            banner = (
                "\n" + "🟢 " * 25 + "\n"
                f"  📱 [DEACTIVATION ALERT — USER IS SAFE AND SOUND: {name.upper()}]\n"
                f"  📞 Recipient Mobile: {phone}\n"
                f"  --------------------------------------------------\n"
                f"{body}\n"
                f"  --------------------------------------------------\n"
                + "🟢 " * 25 + "\n"
            )
            print(banner, flush=True)

            try:
                store_sos_dispatch(session_id, name, phone, title, body, is_critical=False)
            except Exception:
                pass

            sms_otp_service.send_sms_via_gateway(phone, body)

    def get_session_notifications(self, session_id: str) -> List[EmergencyNotificationRecord]:
        return self._session_notifications.get(session_id, [])

    def acknowledge_delivery(self, session_id: str, notification_id: Optional[str] = None, contact_id: Optional[str] = None, recipient_phone: Optional[str] = None, status: NotificationStatusEnum = NotificationStatusEnum.DELIVERED, error_detail: Optional[str] = None) -> Optional[EmergencyNotificationRecord]:
        notifications = self._session_notifications.get(session_id, [])
        if not notifications:
            return None

        record = notifications[-1]
        for recipient in record.recipients:
            if recipient.phone == recipient_phone or recipient.phone_number == recipient_phone or recipient.contact_id == contact_id or (contact_id is None and recipient_phone is None):
                recipient.status = status
                if status == NotificationStatusEnum.DELIVERED:
                    recipient.delivered_at = datetime.utcnow()
                elif status == NotificationStatusEnum.FAILED:
                    recipient.error_detail = error_detail
                    recipient.error_message = error_detail
        return record


notification_store = NotificationOrchestrator()
