import sys
import os
import unittest
from fastapi.testclient import TestClient

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from main import app
from session_service import backend_store
from router import user_profiles
from notification_service import notification_store


class TestPhase7Notifications(unittest.TestCase):

    def setUp(self):
        self.client = TestClient(app)
        self.auth_headers = {"Authorization": "Bearer token_usr_01"}
        backend_store._sessions.clear()
        user_profiles.clear()
        notification_store._session_notifications.clear()

    def test_emergency_notification_dispatch_flow(self):
        # 1. Setup User Profile with 2 Emergency Contacts
        profile_payload = {
            "full_name": "Pravin Kumar",
            "phone_number": "+15550192831",
            "emergency_contacts": [
                {
                    "name": "Guardian Contact 1",
                    "phone": "+15559998888",
                    "relationship": "Family",
                    "is_primary": True,
                    "fcm_token": "fcm_token_valid_01"
                },
                {
                    "name": "Guardian Contact 2",
                    "phone": "+15557776666",
                    "relationship": "Parent",
                    "is_primary": False,
                    "fcm_token": "fcm_token_valid_02"
                }
            ]
        }
        res_profile = self.client.post("/users/profile", json=profile_payload, headers=self.auth_headers)
        self.assertEqual(res_profile.status_code, 201)

        # 2. Activate Emergency Session -> Expect automatic notification dispatch
        res_create = self.client.post("/sessions", json={"user_id": "usr_registered_01"}, headers=self.auth_headers)
        self.assertEqual(res_create.status_code, 201)
        session_data = res_create.json()
        session_id = session_data["session_id"]
        self.assertEqual(session_data["state"], "active")

        # 3. Verify notification record generated automatically with exact SMS alert template
        notifications = session_data["notifications"]
        self.assertEqual(len(notifications), 1)
        notif = notifications[0]
        self.assertEqual(notif["title"], "ABHAYA EMERGENCY ALERT")
        self.assertIn("ABHAYA EMERGENCY ALERT", notif["body"])
        self.assertIn("Pravin Kumar has activated Emergency Mode.", notif["body"])
        self.assertIn("Emergency contact:", notif["body"])
        self.assertIn("Live location:", notif["body"])
        self.assertIn("This alert was generated by ABHAYA.", notif["body"])

        # 4. Verify recipient states for both contacts
        recipients = notif["recipients"]
        self.assertEqual(len(recipients), 2)
        self.assertEqual(recipients[0]["name"], "Guardian Contact 1")
        self.assertEqual(recipients[0]["status"], "delivered")
        self.assertEqual(recipients[1]["name"], "Guardian Contact 2")
        self.assertEqual(recipients[1]["status"], "delivered")

        # 5. Verify GET /sessions/{session_id}/notifications
        res_notif_get = self.client.get(f"/sessions/{session_id}/notifications", headers=self.auth_headers)
        self.assertEqual(res_notif_get.status_code, 200)
        self.assertEqual(len(res_notif_get.json()), 1)

        # 6. Test FCM delivery ACK callback -> Update contact 2 status to FAILED with error detail
        ack_payload = {
            "notification_id": notif["notification_id"],
            "contact_id": recipients[1]["contact_id"],
            "status": "failed",
            "error_detail": "Network timeout on FCM delivery"
        }
        res_ack = self.client.post(f"/sessions/{session_id}/notifications/ack", json=ack_payload, headers=self.auth_headers)
        self.assertEqual(res_ack.status_code, 200)

        # Verify status update in session notifications
        updated_notifs = res_ack.json()["session"]["notifications"]
        updated_recipient = updated_notifs[0]["recipients"][1]
        self.assertEqual(updated_recipient["status"], "failed")
        self.assertEqual(updated_recipient["error_detail"], "Network timeout on FCM delivery")

    def test_duplicate_activation_does_not_spawn_duplicate_notifications(self):
        # 1. First activation
        res_1 = self.client.post("/sessions", json={"user_id": "usr_registered_01"}, headers=self.auth_headers)
        self.assertEqual(res_1.status_code, 201)
        session_id = res_1.json()["session_id"]
        notif_count_1 = len(res_1.json()["notifications"])
        self.assertEqual(notif_count_1, 1)

        # 2. Repeated activation while session is already ACTIVE -> Returns existing session without duplicate notifications
        res_2 = self.client.post("/sessions", json={"user_id": "usr_registered_01"}, headers=self.auth_headers)
        self.assertEqual(res_2.status_code, 201)
        self.assertEqual(res_2.json()["session_id"], session_id)
        notif_count_2 = len(res_2.json()["notifications"])
        self.assertEqual(notif_count_2, 1)  # Must remain 1, no duplicate notification created!


if __name__ == "__main__":
    unittest.main()
